{{- if include "midas.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midas.fullname" . }}
  labels:
    {{- include "midas.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- if .Values.secret.databaseUrl }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secret.authTokens }}
  AUTH_TOKENS: {{ .Values.secret.authTokens | quote }}
  {{- end }}
  {{- if .Values.secret.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.secret.oidcClientSecret | quote }}
  {{- end }}
{{- end }}
