package main

import (
	"fmt"
	"os"
	"path/filepath"
)

// runConfigInit implements `midas config init`.
// It writes a starter midas.yaml to the target path.
// Returns a non-nil error if the file already exists (unless --force is passed).
func runConfigInit(args []string) error {
	target := "midas.yaml"
	force := false

	for i, a := range args {
		switch a {
		case "--force", "-f":
			force = true
		case "--output", "-o":
			if i+1 < len(args) {
				target = args[i+1]
			}
		}
	}

	abs, _ := filepath.Abs(target)

	if !force {
		if _, err := os.Stat(target); err == nil {
			return fmt.Errorf(
				"config init: %s already exists (use --force to overwrite)", abs,
			)
		}
	}

	if err := os.WriteFile(target, []byte(starterConfig), 0644); err != nil {
		return fmt.Errorf("config init: write %s: %w", abs, err)
	}

	fmt.Fprintf(os.Stdout, "Created %s\n", abs)
	fmt.Fprintln(os.Stdout, "Edit this file and set store.backend, auth.mode, and auth.tokens before running in production.")
	return nil
}

// starterConfig is the template written by `midas config init`.
// It is intentionally minimal — operators fill in the relevant sections.
const starterConfig = `# MIDAS Runtime Configuration — generated by 'midas config init'
# See docs/configuration.md for full field reference.
#
# Precedence (highest to lowest):
#   1. Environment variable overrides (MIDAS_*)
#   2. This file
#   3. Built-in defaults

version: 1

# profile: "dev" (permissive) or "production" (postgres + required auth enforced)
profile: dev

server:
  port: 8080
  shutdown_timeout: 15s

store:
  # backend: "memory" (no dependencies, dev only) or "postgres" (production)
  backend: memory
  # dsn: Postgres connection string. Use ${ENV_VAR} to avoid embedding secrets.
  # dsn: "${DATABASE_URL}"
  dsn: ""

auth:
  # mode: "open" (no auth, dev/local only) or "required" (bearer token enforced)
  mode: open
  # tokens: required when mode=required. Token values support ${VAR} expansion.
  # tokens:
  #   - token: "${MIDAS_ADMIN_TOKEN}"
  #     principal: "user:admin"
  #     roles: "admin"
  tokens: []

observability:
  log_level: info
  log_format: json

control_plane:
  enabled: true

dispatcher:
  enabled: false
  publisher: none
  batch_size: 100
  poll_interval: 2s
  max_backoff: 30s

kafka:
  brokers: []
  client_id: midas
  required_acks: -1
  write_timeout: 0s
`
